name: Build Spring Boot JAR

on:
  push:
    branches: [ "master" ]  # Change from "main" to "master"
  pull_request:
    branches: [ "master" ]  # Change from "main" to "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: stock-market-app-jar
          path: target/*.jar
